# Generated by Django 3.0 on 2019-08-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMarApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_date', models.DateTimeField()),
                ('exam_weight', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_description', models.CharField(max_length=500)),
                ('plan_start_date', models.DateTimeField()),
                ('plan_end_date', models.DateTimeField()),
                ('exam_progress_unit', models.CharField(choices=[('OB', 'Por objetivos'), ('TM', 'Por tiempo')], default='OB', max_length=2)),
                ('create_timetable', models.BooleanField(default=False)),
                ('use_spacing', models.BooleanField(default=False)),
                ('session_design', models.BooleanField(default=False)),
                ('session_style', models.CharField(blank=True, choices=[('MX', 'Sesion mixta'), ('BL', "'Full block'")], max_length=2, null=True)),
                ('fixed_timetable', models.BooleanField(default=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('MO', 'lunes'), ('TU', 'martes'), ('WE', 'miercoles'), ('TH', 'jueves'), ('FR', 'viernes'), ('SA', 'sabado'), ('SU', 'domingo')], max_length=2)),
                ('time_slot_start', models.TimeField()),
                ('time_slot_end', models.TimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('area_description', models.CharField(max_length=500)),
                ('area_weight', models.IntegerField()),
                ('area_priority', models.IntegerField()),
                ('area_progress_unit', models.CharField(choices=[('OB', 'Por objetivos'), ('TM', 'Por tiempo')], default='OB', max_length=2)),
                ('area_unit', models.CharField(choices=[('PG', 'paginas'), ('EX', 'ejercicios'), ('TP', 'temas'), ('ST', 'subtemas'), ('TM', 'tiempo')], default='PG', max_length=2)),
                ('content_quantity', models.IntegerField()),
                ('laps', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.Plan')),
            ],
        ),
    ]
