# Generated by Django 3.0 on 2019-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMarApp', '0002_areas_exam_plan_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='mixable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='area_unit',
            field=models.CharField(choices=[('PG', 'paginas'), ('EX', 'ejercicios'), ('TP', 'temas'), ('SL', 'diapositivas'), ('ST', 'subtemas'), ('TM', 'tiempo')], default='PG', max_length=2),
        ),
        migrations.AlterField(
            model_name='areas',
            name='content_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='areas',
            name='laps',
            field=models.IntegerField(default=1),
        ),
    ]
