# Generated by Django 3.0 on 2019-08-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMarApp', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_estimate',
            field=models.IntegerField(default=40),
        ),
    ]
