# Generated by Django 3.0 on 2019-08-04 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMarApp', '0003_exam_time_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_studied', models.IntegerField()),
                ('time_taken', models.IntegerField()),
                ('session_date', models.DateTimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.Exam')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudyMarApp.User')),
            ],
        ),
    ]
