# Generated by Django 3.0 on 2019-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudyMarApp', '0004_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='speed',
            field=models.IntegerField(default=40),
        ),
    ]
